export const initialState = {
  activ: true,
  articul: "",
  barCodeExists: false,
  barkod: "",
  brutto: 0,
  buying: 0,
  code: "",
  cost: 0,
  count: 0,
  countryOfManufacturerId: "",
  deleteStatus: false,
  groupId: "",
  id: "",
  imageUrl: "",
  info: "",
  limit: 0,
  modelId: "",
  nameOfManufacturer: "",
  nameUnitOne: null,
  netto: 0,
  note: "",
  productName: "",
  qrCode: "",
  qrCodeExists: false,
  quantity: 0,
  rowNum: 0,
  selling: 0,
  size: "",
  unitOfMeasurementOneId: "",
  unitOfMeasurementTwoId: "",
  volume: 0,
};

export const invoiceProductInitialState = {
  id: "",
  invoiceId: "",
  productId: "",
  productName: "",
  storeIdFirst: "",
  storeNameFirst: "",
  storeIdSecond: "",
  storeNameSecond: "",
  clientId: "",
  clientName: "",
  sellingAmount: 0,
  buyingAmount: 0,
  invoiceNum: 0,
  quantity: 0,
  selling: 0,
  buying: 0,
  cost: 0,
  count: 0,
  discount: 0,
  discountPrice: 0,
  amount: 0,
  discountAmount: 0,
  barkod: "",
  code: "",
  articul: "",
  note: "",
  size: "",
  benefit: 0,
  deleteStatus: false,
  date: new Date().toLocaleDateString(),
  dateLimit: new Date().toLocaleDateString(),
  operation: "selling",
  operationEnum: 0,
  correctStatus: "",
  selectedForRemoving: false,
  compared: false,
  version: "",
};

export const invoiceInitialState = {
  invoiceId: "",
  storeIdFirst: "",
  storeIdSecond: "",
  clientId: "",
  date: new Date().toLocaleDateString(),
  totalAmount: 0,
  benefit: 0,
  note: "",
  invoiceNumber: 0,
  deleteStatus: false,
  dateLimit: new Date().toLocaleDateString(),
  operation: "selling",
  listProduct: [],
  imageUrl: "",
};
